name: 'Test my project'
on:
  push:
 
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Build images.'
        run: docker-compose build
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: 'Test.'
        run: docker-compose up

