name: 'Test my project'
on:
  push:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: 'Build.'
        run: docker-compose build
      - uses: actions/upload-artifact@master
        with:
          name: docker-images
  test:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: docker-images
      - uses: actions/checkout@v2
      - name: 'Test.'
        run: docker-compose up
