name: 'Test my project'
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build images.'
        run: docker-compose build
      - name: 'Test.'
        run: docker-compose up
      - if: ${{.State.ExitCode != 0}}
        name: 'Deploy'
        run: echo 'Deploy service!'
