name: 'Test my project'
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: 'Build images.'
        run: docker-compose build
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ghat/Dockerfile
          tags: images:latest
          outputs: type=docker,dest=/tmp/images.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: /tmp/images.tar
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
        
      - name: Load Docker images from previous workflows
        run: |
          docker load --input image.tar
      - name: 'Test.'
        run: docker-compose up
