name: 'Test my project'
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build.
        run: docker-compose build
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: 'Test.'
        run: docker-compose up
