name: 'Test my project'
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build.
        run: docker-compose build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: /tmp/images.tar
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
        
      - name: Load Docker images from previous workflows
        run: |
          docker load --input image.tar
      - name: 'Test.'
        run: docker-compose up
