name: 'Test my project'
on:
  push:
 
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Build images.'
        run: docker-compose build
        
      - name: 'Push images.'
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
      - name: 'Test.'
        run: docker-compose up

