name: 'Test my project'
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build.
        run: docker-compose build

      - name: Test.
        run: docker-compose up
        
      - name: Exit code.
        run: docker inspect gh_actions_test_tests_1 --format='{{.State.ExitCode}}'
        
      - name: Check exit code.
        run: echo "ECODE=$(docker inspect gh_actions_test_tests_1 --format='{{.State.ExitCode}}')" >> env.EXITCODE
      
      - if: ${{ env.EXITCODE == 0 }}
        name: Deply.
        run: echo "Deploy!."
